### ISSUE TITLE
Angular 17 Update

### ISSUE THREAD

**Issue by lynchdavis** [shaninalex/angular-go-kratos-ui#15]
The recent release of the Angular 17 and the default stand-alone for components has made some integrations a little more interesting.  Do you have any intention of upgrading your code to support it?

Also, do you actually try to use the @ory/kratos-client for the UI to communicate with Kratos?  I was looking around for this, but could not find if you were leveraging their code.

Thanks,

**Comment by shaninalex** [comment]
@lynchdavis Hello! 
Yes, I'll update to angular 17. New template language seems to be more... lightweight? Less ngFor and ngIf , and more @for and @if makes templates more readable.

I was using only [kratos-selfservice-ui-node](https://github.com/ory/kratos-selfservice-ui-node) but it hard to customize styles to make look like an actual application.

**Comment by shaninalex** [comment]
@lynchdavis 
Updated to angular 17 - PR: https://github.com/shaninalex/angular-go-kratos-ui/pull/16

You can now check out updated templates.
